server:
  port: 8001

spring:
  application:
    name: store-gateway

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  # 可以显示服务的真实IP 地址

zuul:
  routes:
    store-good: #这里是一个map, key 值是任意的
      path: /sys/**
      serviceId: store-good
      stripPrefix: false  # 表示代理的时候是否要取消前缀 例如 /store/get/1 如果配置为true 则表示 代理转发到 /get/1

